---
- name: load fileserver
  hosts: fileserver
  become: true
  collections:
     - community.sap_launchpad

  ### This playbook downloads all the SAP files required for installing
  ### SAP HANA and S/4 HANA from Maintenance Planner
  ### This script requires the following variables as input
  #
  # required:
  #   suser_id                 : SAP Credentials required for download
  #   suser_password
  #
  # optional:
  #   download_path           : Pfad in den die Software heruntergeladen wird
  #   venv                     : virtuelles Python environment für prereqs 
  #
  # vars_prompt:
  #  - name: "suser_id"
  #    prompt: "S-User ID"
  #    private: false
  #    default: "{{lookup('env', 'SAP_SUPPORT_DOWNLOAD_USERNAME')}}"
  #  - name: "suser_password"
  #    prompt: "S-User PW"
  #    private: true
  #    default: "{{lookup('env', 'SAP_SUPPORT_DOWNLOAD_PASSWORD')}}"

  vars:
      download_path: /sap-software

  vars_files: sap-dl.yml

  tasks:
    - name: ensure S-USER and PASSWORD are defined
      ansible.builtin.fail:
            msg: "Please set suser_id and suser_password"
      when: ( suser_id|trim ==''  )  or  ( suser_password|trim == '' )
      tags:
        - sap_s4_softwaredownload
        - sap_extra_download

    - name: ensure prereqs are installed
      pip:
        name:
          - urllib3
          - beautifulsoup4
          - lxml
          - requests
        state: present
        virtualenv: "{{ venv | default(omit) }}"

    - name: Ensure download directories exist
      file:
         path: "{{ item }}"
         state: directory
         mode: '0755'
      loop:
        - "{{ download_path }}"
        - "{{ download_path }}/HANA2SPS06"
        - "{{ download_path }}/S4HANA2021.FNDN"

    - name: download SAPCAR
      community.sap_launchpad.software_center_download:
        suser_id: "{{ suser_id }}"
        suser_password: "{{ suser_password }}"
        softwarecenter_search_query: "{{ item }}"
        dest: "{{ download_path }}"
        dry_run: "{{ dryrun|default(false) }}"
      loop: "{{ sapcar }}"
      ignore_errors: true

    - name: download Hana Media
      community.sap_launchpad.software_center_download:
        suser_id: "{{ suser_id }}"
        suser_password: "{{ suser_password }}"
        softwarecenter_search_query: "{{ item }}"
        dest: "{{ download_path }}/HANA2SPS06"
        dry_run: "{{ dryrun|default(false) }}"
      loop: "{{ hdb2sps06 }}"
      ignore_errors: true

    - name: download S4 Media
      community.sap_launchpad.software_center_download:
        suser_id: "{{ suser_id }}"
        suser_password: "{{ suser_password }}"
        softwarecenter_search_query: "{{ item }}"
        dest: "{{ download_path }}/S4HANA2021.FNDN"
        deduplicate: "last"
        dry_run: "{{ dryrun|default(false) }}"
      loop: "{{ s4fndn2021 + swpm }}"
      ignore_errors: true

    - name: Link SAPCAR
      ansible.builtin.file:
        src: '{{ download_path }}/{{ sapcar | first }}'
        dest: '{{ item }}'
        state: hard
        mode: '755'
      loop:
        - '{{ download_path }}/S4HANA2021.FNDN/{{ sapcar | first }}'
        - '{{ download_path }}/HANA2SPS06/{{ sapcar | first }}'
    
   
