---
# TODO CHECK/SET Variables
- name: Verify that variable node_ip is set
  ansible.builtin.assert:
    that: not( ( item.node_ip is undefined) or ( item.node_ip is none) or ( item.node_ip | trim == '') )
    msg: "Variable 'node_ip' is undefined or empty. Please define it your host list"

- name: Verify that variable node_name is set
  ansible.builtin.assert:
    that: not( ( item.node_name is undefined) or ( item.node_name is none) or ( item.node_name | trim == '') )
    msg: "Variable 'node_name' is undefined or empty. Please define it your host list"

- name: Ensure node_domain is set
  ansible.builtin.set_fact:
    __update_etc_hosts_domain: "{{ item.node_domain | default(sap_domain | default(ansible_domain)) }}"

- name: Verify that variable domain_name is set
  ansible.builtin.assert:
    that: >
      not( ( __update_etc_hosts_domain is undefined) or
      ( __update_etc_hosts_domain is none) or
      ( __update_etc_hosts_domain | trim == '') )
    msg: "Variable 'node_name' is undefined or empty. Please define it your host list"

- name: Set default values
  ansible.builtin.set_fact:
    __update_etc_hosts_comment: "{{ ( item.comment|d('') + ' ' + item.hana_site|d('') ) | trim }}"
    __update_etc_hosts_alias_mode: "{{ item.alias_mode | default('merge') }}"
    __update_etc_hosts_state: "{{ item.state | default('present') }}"

- name: Get all existing hostname aliases of {{ item.node_ip }}
  ansible.builtin.shell: |
    awk '( $1 == "{{ item.node_ip }}" ) {
      for (i=2; i<=NF; ++i) {
        if ( $i == "#" ) { break }
        if (( $i != "{{ item.node_name }}" ) && ( $i != "{{ item.node_name }}.{{ __update_etc_hosts_domain }}" )) { printf " "$i }
      }
    }' /etc/hosts
  register: __update_etc_hosts_register_aliases
  changed_when: false
  when: __update_etc_hosts_alias_mode != "overwrite"

- name: Add defined aliases
  ansible.builtin.set_fact:
    # __update_etc_hosts_aliases: "{{ __update_etc_hosts_register_aliases.stdout.split[' '] + item.node_aliases| d([''])|uniq|join(' ') }}"
    __update_etc_hosts_aliases: "{{ __update_etc_hosts_register_aliases.stdout }}"
# TODO: ADD or replace by item.aliases

- name: Display host and domain name, and IP address before the modification
  ansible.builtin.debug:
    msg:
      - "hostname = {{ item.node_name }}"
      - "domain   = {{ __update_etc_hosts_domain }}"
      - "ip       = {{ item.node_ip }}"
      - "comment  = {{ __update_etc_hosts_comment }}"
      - "aliases  = {{ item.aliases | d('') }}"
      - "alias mode = {{ __update_etc_hosts_alias_mode }}"
      - "state      = {{ __update_etc_hosts_state }}"

- name: Display hostname aliases
  ansible.builtin.debug:
    var: __update_etc_hosts_aliases

- name: Check if ipv4 address, FQDN, and hostname are in /etc/hosts
  block:
    - name: Perform the /etc/hosts completeness check
      ansible.builtin.command: awk 'BEGIN{a=0}/{{ item.node_ip }}/&&/{{ item.node_name }}.{{ __update_etc_hosts_domain }}/&&/{{ item.node_name }}/{a++}END{print a}' /etc/hosts
      register: __update_etc_hosts_register_ipv4_fqdn_sap_hostname_once_check
      changed_when: false

    - name: Display the output of the /etc/hosts completeness check
      ansible.builtin.debug:
        var: __update_etc_hosts_register_ipv4_fqdn_sap_hostname_once_check.stdout_lines,
              __update_etc_hosts_register_ipv4_fqdn_sap_hostname_once_check.stderr_lines

    - name: Display the expected output of the /etc/hosts completeness check
      ansible.builtin.debug:
        msg:
          - "Expected:"
          - "{{ item.node_ip }} {{ item.node_name }}.{{ __update_etc_hosts_domain }} {{ item.node_name }}"
      when:
        - __update_etc_hosts_register_ipv4_fqdn_sap_hostname_once_check.stdout != "1"

    - name: Fail if ip4 address, FQDN, or hostname are not in /etc/hosts
      ansible.builtin.fail:
        msg:
          - "Server's ip4 address, FQDN, or hostname are not in /etc/hosts!"
          - "Expected:"
          - "{{ item.node_ip }} {{ item.node_name }}.{{ __update_etc_hosts_domain }} {{ item.node_name }}"
      when:
        - __update_etc_hosts_register_ipv4_fqdn_sap_hostname_once_check.stdout != "1"
      ignore_errors: "{{ ansible_check_mode }}"

# We allow more than one line containing sap_ip:
- name: Check for duplicate entries of {{ item.node_ip }}
  ansible.builtin.shell: |
    n=$(grep "^{{ item.node_ip }}\s" /etc/hosts | wc -l)
    if [ $n -gt 1 ]; then
      echo "Duplicate IP entry in /etc/hosts!"
      exit 1
    else
      exit 0
    fi
  register: __update_etc_hosts_register_duplicate_ip_check
  changed_when: false
  ignore_errors: yes
  when: not ansible_check_mode

- name: Report if there is more than one line with the IP address
  ansible.builtin.debug:
    msg:
      - "More than one line containing {{ item.node_ip }}. File /etc/hosts will not be modified."
  when:
    - not ansible_check_mode
    - __update_etc_hosts_register_duplicate_ip_check.stdout == 'Duplicate IP entry in /etc/hosts!'

- name: Ensure that the entry in /etc/hosts is correct
  ansible.builtin.lineinfile:
    path: /etc/hosts
    regexp: '^{{ item.node_ip }}\s'
    line: "{{ item.node_ip }} {{ item.node_name }}.{{ __update_etc_hosts_domain }} {{ item.node_name }}{{ __update_etc_hosts_aliases }}"
    backup: yes
  when:
    - not ansible_check_mode
    - __update_etc_hosts_register_duplicate_ip_check.stdout != 'Duplicate IP entry in /etc/hosts!'
# TODO: Add comment

- name: Check for duplicate or missing entries of hostname and fqdn in /etc/hosts
  ansible.builtin.shell: |
    n=$(awk 'BEGIN{a=0}/^{{ line_item }}\s/||/\s{{ line_item }}\s/||/\s{{ line_item }}$/{a++}END{print a}' /etc/hosts)
    if [ $n -eq 1 ]; then
      exit 0
    else
      exit 1
    fi
  loop:
    - '{{ item.node_name }}.{{ __update_etc_hosts_domain }}'
    - '{{ item.node_name }}'
  changed_when: false
  loop_control:
    loop_var: line_item
  when: not ansible_check_mode
