---
####################################################
#
# Phase 2: Basic OS Setup
#
# This playbook covers the following configuration steps
#  - network
#  - timesync
#  - storage customization
#  - subscription

# Variables for parameterizing this playbook are stored
# either in hostvars/groupvars directory or in the corresponding
# inventory settings in AWX or Controller

- name: Phase 2 - basic OS Setup
  hosts: "{{ targethosts | d('sap') }}"
  become: true

  tasks:
    - name: Ensure network is configured correctly
      when: network_connections is defined
      ansible.builtin.include_role:
        name: fedora.linux_system_roles.network

    - name: Ensure timesync is configured correctly
      when: (timesync_ntp_servers is defined) or (timesync_ptp_domains is defined)
      ansible.builtin.include_role:
        name: fedora.linux_system_roles.timesync

    # Read role description, if you want username/password authentication
    - name: Ensure system is properly subscribed
      when: >
        (rhsm_org is defined) and 
        (rhsm_key is defined)
      ansible.builtin.include_role:
        name: fedora.linux_system_roles.rhc
      vars:
        rhc_state: present
        rhc_organization: "{{ rhsm_org }}"
        rhc_auth:
          activation_keys:
            keys: [ "{{ rhsm_key }}" ]

    - name: Configure storage
      when: (server_def is defined)
      block:
        - name: Get storage pool setup from server name definition
          ansible.builtin.set_fact:
            storage_pools: "{{ server_def | selectattr('name', 'equalto', inventory_hostname) | sum(attribute='storage_pools', start=[]) }}"
          when:
            - server_def | selectattr('name', 'defined') | map(attribute='name') | list | length > 0
            - inventory_hostname in (server_def|map(attribute='name')|list)

        - name: Get storage pool setup from server group definition
          ansible.builtin.set_fact:
            storage_pools: "{{ server_def | selectattr('group', 'in', group_names) | sum(attribute='storage_pools', start=[]) }}"
          when:
            - (storage_pools is undefined) or (storage_pools| list | length == 0)
            - server_def | selectattr('group', 'defined') | map(attribute='group') | list | length > 0

        - name: Ensure storage is configured correctly
          ansible.builtin.include_role:
            name: fedora.linux_system_roles.storage
          when:
            - storage_pools is defined
            - storage_pools | list | length > 0
