name: Dump Data

on:
  repository_dispatch:
    types: [dump_data]

jobs:
  dump_data_job:
    runs-on: ubuntu-latest
    steps:
      - name: Dump Parameters
        run: |
          # Die übergebenen Parameter aus dem JSON-Payload erhalten
          nickname=${{ github.event.client_payload.nickname }}
          email=${{ github.event.client_payload.email }}
          # Ergebnis ausgeben
          echo "Der Nutzer ${nickname} hat die email ${email}"
          # Launch Job in AAP
          curl -k -X POST \
            --url https://${{ secrets.AAP_HOST }}/api/v2/job_templates/185/launch/ \
            --oauth2-bearer "${{ secrets.AAP_DEPLOY_TOKEN }}" \
            -H 'Content-Type: application/json' \
            -d '{ "extra_vars": { "${{ github.event.client_payload }}" } }'
